theme: jekyll-theme-cayman

title: Customer ID Capture
description: Scan machine readable identiy cards and forward to cloud
show_releases: true
release_url: https://github.com/tony-mowers/pos_id_capture/releases/latest
